// auto generated by: scim-sdk-schema-pojo-creator
package de.captaingoldfish.restclient.scim.endpoints;

import java.util.Arrays;

import de.captaingoldfish.restclient.scim.constants.ClasspathReferences;
import de.captaingoldfish.restclient.scim.resources.ScimProviderMetadata;
import de.captaingoldfish.scim.sdk.common.utils.JsonHelper;
import de.captaingoldfish.scim.sdk.server.endpoints.EndpointDefinition;
import de.captaingoldfish.scim.sdk.server.endpoints.ResourceHandler;


public class ProviderMetadataEndpointDefinition extends EndpointDefinition
{

  public ProviderMetadataEndpointDefinition(ResourceHandler<ScimProviderMetadata> resourceHandler)
  {
    super(JsonHelper.loadJsonDocument(ClasspathReferences.PROVIDER_METADATA_RESOURCE_TYPE),
          JsonHelper.loadJsonDocument(ClasspathReferences.PROVIDER_METADATA_SCHEMA), Arrays.asList(), resourceHandler);
  }
}
