// auto generated by: scim-sdk-schema-pojo-creator
package de.captaingoldfish.restclient.application.endpoints.metadata;

import java.util.ArrayList;
import java.util.List;
import java.util.Optional;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.node.ObjectNode;
import com.nimbusds.openid.connect.sdk.op.OIDCProviderMetadata;

import de.captaingoldfish.restclient.application.utils.Utils;
import de.captaingoldfish.restclient.database.entities.OpenIdProvider;
import de.captaingoldfish.restclient.database.repositories.OpenIdProviderDao;
import de.captaingoldfish.restclient.scim.resources.ScimProviderMetadata;
import de.captaingoldfish.scim.sdk.common.constants.enums.SortOrder;
import de.captaingoldfish.scim.sdk.common.exceptions.ResourceNotFoundException;
import de.captaingoldfish.scim.sdk.common.schemas.SchemaAttribute;
import de.captaingoldfish.scim.sdk.server.endpoints.Context;
import de.captaingoldfish.scim.sdk.server.endpoints.ResourceHandler;
import de.captaingoldfish.scim.sdk.server.filter.FilterNode;
import de.captaingoldfish.scim.sdk.server.response.PartialListResponse;
import lombok.RequiredArgsConstructor;


/**
 *
 */
@RequiredArgsConstructor
public class ProviderMetadataResourceHandler extends ResourceHandler<ScimProviderMetadata>
{


  private final OpenIdProviderDao openIdProviderDao;

  /**
   * {@inheritDoc}
   */
  @Override
  public ScimProviderMetadata createResource(ScimProviderMetadata resource, Context context)
  {
    // disabled
    return resource;
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public ScimProviderMetadata getResource(String id,
                                          List<SchemaAttribute> attributes,
                                          List<SchemaAttribute> excludedAttributes,
                                          Context context)
  {

    Long openIdProviderId = Utils.parseId(id);
    OpenIdProvider openIdProvider = openIdProviderDao.findById(openIdProviderId).orElseThrow(() -> {
      return new ResourceNotFoundException(String.format("OpenID Client with id '%s' does not exist", id));
    });
    Optional<OIDCProviderMetadata> oidcMetadata = Optional.ofNullable(Utils.loadDiscoveryEndpointInfos(openIdProvider));
    Optional<ObjectNode> oid4vciMetadata = Utils.loadOidc4vciDiscoveryEndpointInfos(openIdProvider);

    return ScimProviderMetadata.builder()
                               .oidcMetadata(oidcMetadata.map(OIDCProviderMetadata::toString).orElse(null))
                               .oid4vciMetadata(oid4vciMetadata.map(JsonNode::toString).orElse(null))
                               .build();
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public PartialListResponse<ScimProviderMetadata> listResources(long startIndex,
                                                                 int count,
                                                                 FilterNode filter,
                                                                 SchemaAttribute sortBy,
                                                                 SortOrder sortOrder,
                                                                 List<SchemaAttribute> attributes,
                                                                 List<SchemaAttribute> excludedAttributes,
                                                                 Context context)
  {
    // TODO
    return PartialListResponse.<ScimProviderMetadata> builder().resources(new ArrayList<>()).totalResults(0).build();
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public ScimProviderMetadata updateResource(ScimProviderMetadata resource, Context context)
  {
    // disabled
    return resource;
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public void deleteResource(String id, Context context)
  {
    // TODO
  }
}
