// auto generated by: scim-sdk-schema-pojo-creator
package de.captaingoldfish.restclient.scim.resources;

import java.util.Arrays;
import java.util.Optional;

import de.captaingoldfish.scim.sdk.common.resources.ResourceNode;
import de.captaingoldfish.scim.sdk.common.resources.complex.Meta;
import lombok.Builder;



/**
 * Contains the metadata of an OpenID Connect Provider / Credential Issuer.
 */
public class ScimProviderMetadata extends ResourceNode
{

  public ScimProviderMetadata()
  {
    setSchemas(Arrays.asList(FieldNames.SCHEMA));
  }

  @Builder
  public ScimProviderMetadata(String id, Meta meta, String oidcMetadata, String oid4vciMetadata)
  {
    setSchemas(Arrays.asList(FieldNames.SCHEMA));
    setId(id);
    setMeta(meta);
    setOidcMetadata(oidcMetadata);
    setOid4vciMetadata(oid4vciMetadata);
  }

  /**
   * The complete JSON representation of the OpenID Connect Discovery Document.
   */
  public Optional<String> getOidcMetadata()
  {
    return getStringAttribute(FieldNames.OIDCMETADATA);
  }

  /**
   * The complete JSON representation of the OpenID Connect Discovery Document.
   */
  public void setOidcMetadata(String openIdMetadata)
  {
    setAttribute(FieldNames.OIDCMETADATA, openIdMetadata);
  }

  /**
   * The complete JSON representation of the Credential Issuer Discovery Document.
   */
  public Optional<String> getOid4vciMetadata()
  {
    return getStringAttribute(FieldNames.OID4VCIMETADATA);
  }

  /**
   * The complete JSON representation of the Credential Issuer Discovery Document.
   */
  public void setOid4vciMetadata(String credentialIssuerMetadata)
  {
    setAttribute(FieldNames.OID4VCIMETADATA, credentialIssuerMetadata);
  }


  /**
   * contains the attribute names of the resource representation
   */
  public static class FieldNames
  {

    public static final String SCHEMA = "urn:ietf:params:scim:schemas:captaingoldfish:2.0:ProviderMetadata";

    public static final String OIDCMETADATA = "oidcMetadata";

    public static final String OID4VCIMETADATA = "oid4vciMetadata";
  }
}
